### ISSUE TITLE
Clone a VM not working

### ISSUE THREAD

**Issue by PeterDepreitere** [Artilium/GiG-ePortal#18]

**Comment by PeterDepreitere** [comment]
Your service request could not be fulfilled correctly, please contact support and mention "eco-1001-ccc1a252-e3f2-c72a-23cc-419ce01b2d34"

**Comment by PeterDepreitere** [comment]
@hofkensj @yveskerwyn nemen jullie deze op aub?

**Comment by hofkensj** [comment]
any reference ?

**Comment by PeterDepreitere** [comment]
Nope, was zo in de lijst van Yves genoteerd. Weet niet door wie of op welk platform.

**Comment by hteibler** [comment]
this happens when you try to clone a VM 
https://be-scale-1.demo.greenitglobe.com/cbgrid/Virtual%20Machine?id=486
action --> clone
error: Your service request could not be fulfilled correctly, please contact support and mention "eco-1001-ccc1a252-e3f2-c72a-23cc-419ce01b2d34"

**Comment by PeterDepreitere** [comment]
@hofkensj @yveskerwyn nemen jullie deze op aub?

**Comment by yveskerwyn** [comment]
Filed as a bug in: https://github.com/0-complexity/openvcloud/issues/824

**Comment by yveskerwyn** [comment]
Bug got fixed in a new build of OVC v2.1.7

I will request a pull of the most recent build

**Comment by PeterDepreitere** [comment]
To be released. Under control of GiG.
