### ISSUE TITLE
ePortal installation guide

### ISSUE THREAD

**Issue by daliusl** [Artilium/GiG-ePortal#23]
Can we please get ePortal installation with required system parameters

**Comment by PeterDepreitere** [comment]
hi @daliusl 
For what system is this? For what purpose is this?

**Comment by PeterDepreitere** [comment]
What do you mean with 'required system parameters'?

**Comment by daliusl** [comment]
Hi Peter,

I need to setup ePortal on our new environment and I would like to have installations guide such minimum RAM required, storage size etc. Also steps to be taken to instal on windows and Linux machines 

Thanks,
Dalius

**Comment by daliusl** [comment]
Hey Guys,
Any updated on installation guidebook?

**Comment by hofkensj** [comment]
any update on this ?

**Comment by PeterDepreitere** [comment]
ePortal is deployed by Artilium. The parameters in following web page need to be filled before deployment can start: https://docs.google.com/forms/d/e/1FAIpQLSduRRATLtF_iH1k98apAVHPoCPZ1sXTVJd7N7Y5jtZlsdr3ng/viewform?c=0&w=1
