### ISSUE TITLE
Mauritius LCI - cannot give access to VDC to user through the ePORTAL

### ISSUE THREAD

**Issue by hofkensj** [Artilium/GiG-ePortal#24]
{"message":"Blueprint ays\/repository\/4b33LCITesting\/blueprint\/LCITest_addusers24cccould not be executed","stacktrace":""}

Nicolas Drury created script:
Hi all, the script is ready. It can be run on the CLI and is dynamic so a seperate repo/vdc/user will be created every time the script is ran. The issue we were facing yesterday seems to be resolved (we got no steps in the last CURL request). Now we're facing other issues, in the FE we can create repo's, vdc's and users but no customers.

**Comment by PeterDepreitere** [comment]
Issue on Cockpit, nor ARTA related. Tracked as well in GiG Gogs
